### ISSUE TITLE
On linux currently anything below electron 10 has a flickering issue lol

### ISSUE THREAD

**Issue by thecountrox** [y9x/client#2]

**Comment by e9x** [comment]
Versions of Electron later than version 7 have an issue with mouse input blocking networking. Try it: On electron 10, enter a Krunker lobby and hold down the left mouse button while moving your mouse. Network packets should slow down. 
This issue cannot be resolved because of this game-breaking behavior.

**Comment by thecountrox** [comment]
> 

actually electron 10 on linux ( i think its bad on windows tho) works just fine

**Comment by thecountrox** [comment]
uh it works on janrex client where i changed it to electron 10 i dont see why it shouldnt work here

**Comment by e9x** [comment]
Yes, Electron 10 will work on Linux without issues but the stuttering will happen on Windows.
